export const KEY_UPDATE = 'KEY_UPDATE';
export const SOCKET_SET_USERS_IDS = 'SOCKET_SET_USERS_IDS';
export const SOCKET_SET_USER = 'SOCKET_SET_USER';
export const SOCKET_REQ_PARTNER = 'SOCKET_REQ_PARTNER';
export const SOCKET_REQ_PARTNER_CONFIRM = 'SOCKET_REQ_PARTNER_CONFIRM';

